development:
  bucket: techbo-dev
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
  s3_region: ap-northeast-1
test:
  bucket: techbo-test
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
  s3_region: us-west-2
production:
  bucket: techbo-production
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
  s3_host_name: s3-ap-northeast-1.amazonaws.com
  s3_region: ap-northeast-1
